version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my_network
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Nithin#7786
      MYSQL_DATABASE: employee_management
    networks:
      - my_network

networks:
  my_network:
